//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RubikSolver.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RubikSolver.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animate.
        /// </summary>
        internal static string Animate {
            get {
                return ResourceManager.GetString("Animate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back .
        /// </summary>
        internal static string Back_Side {
            get {
                return ResourceManager.GetString("Back_Side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Botton .
        /// </summary>
        internal static string Bottom_Side {
            get {
                return ResourceManager.GetString("Bottom_Side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change &amp;language.
        /// </summary>
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clockwise.
        /// </summary>
        internal static string Clockwise {
            get {
                return ResourceManager.GetString("Clockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Error.
        /// </summary>
        internal static string Configuration_Error {
            get {
                return ResourceManager.GetString("Configuration_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter clockwise.
        /// </summary>
        internal static string Counter_clockwise {
            get {
                return ResourceManager.GetString("Counter_clockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cube mis-oriented.  If the configuration you have entered is indeed what you have,
        ///then your cube appears to have been disassembled, and re-assembled incorrectly.
        ///Check configuration and try again..
        /// </summary>
        internal static string Cube_mis_oriented {
            get {
                return ResourceManager.GetString("Cube_mis_oriented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cube does not contain proper cubelets.  Check configuration and try again..
        /// </summary>
        internal static string Does_not_contain_proper_cubelets {
            get {
                return ResourceManager.GetString("Does_not_contain_proper_cubelets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        internal static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front .
        /// </summary>
        internal static string Front_Side {
            get {
                return ResourceManager.GetString("Front_Side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left .
        /// </summary>
        internal static string Left_Side {
            get {
                return ResourceManager.GetString("Left_Side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves.
        /// </summary>
        internal static string Moves {
            get {
                return ResourceManager.GetString("Moves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Quit.
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right .
        /// </summary>
        internal static string Right_Side {
            get {
                return ResourceManager.GetString("Right_Side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle.
        /// </summary>
        internal static string Shuffle {
            get {
                return ResourceManager.GetString("Shuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solve.
        /// </summary>
        internal static string Solve {
            get {
                return ResourceManager.GetString("Solve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top .
        /// </summary>
        internal static string Top_Side {
            get {
                return ResourceManager.GetString("Top_Side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable To Solve Cube.
        /// </summary>
        internal static string Unable_To_Solve_Cube {
            get {
                return ResourceManager.GetString("Unable_To_Solve_Cube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        internal static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese.
        /// </summary>
        internal static string Vietnamese {
            get {
                return ResourceManager.GetString("Vietnamese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your cube!.
        /// </summary>
        internal static string Your_cube {
            get {
                return ResourceManager.GetString("Your_cube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
